### PR TITLE
Catalog: Create unit tests, Book and Label classes and App class methods

### PR DESCRIPTION
**Pull request by Timbar09**
In this PR, I implemented the Test Driven Development(TDD) approach and created unit tests for 2 classes.

**Changes**

- Added unit tests for methods of the `Book` class.
- Added unit tests for methods of the `Label` class.
- Created the `Book` and `Label` classes in separate files, including their individual methods.
- Added the `all_methods.rb` file in the `./spec` folder which helps navigate between classes and test files.
- Updated the `Item` class constructor arguments as well as the `can_be_achieved?` and `move_to_archive` methods.
- Added the `add_book`, `add_label`, `list_all_books`, and `list_all_labels` methods in the App class.
- Refactored the `do_action`method in the DisplayItems class.

### CODE REVIEW

**Review by aubinleyoung — COMMENTED** [review]
Hey @Timbar09 ,
While you made a great effort in this PR, I understand that you implemented the Test Driven Development(TDD) approach but unfortunately, according to [Microverse code review](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md)  I cannot proceed to review your code.

# Failed linter checks 🔴 

You have submitted a PR, that doesn't pass the linter rules for this project. Kindly add all tested methods to resolve the errors and follow [best practices for Ruby](https://github.com/microverseinc/curriculum-ruby/blob/main/articles/ruby_best_practices.md).

**Comment by Timbar09** [comment]
Thank you for the review. Changes are on the way.

**Review by Tobby8629 — APPROVED** [review]
Hi @Timbar09 

## APPROVED 🟢

## Highlights
✔️ Passing tests
✔ App running properly
✔ No linter errors

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------

**Comment by Timbar09** [comment]
Thanks for approving the changes @Tobby8629 🙏. I'll go ahead and merge the branch to the `dev` branch. 🙃

**Pull request merged**
